export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const SET_MODAL_LOGIN = "SET_MODAL_LOGIN";
export const SET_CHART_PRODUCT = "SET_CHART_PRODUCT";
export const SET_MODAL_RETURN_PENDING = "SET_MODAL_RETURN_PENDING";
export const SET_MODAL_WAITING_FOR_PAYMENT = "SET_MODAL_WAITING_FOR_PAYMENT"
export const SET_MODAL_PENDING = "SET_MODAL_PENDING"
export const SET_CHECKOUT_PRODUCT = "SET_CHECKOUT_PRODUCT"
export const SET_MODAL_CONFIRM_PAYMENT = "SET_MODAL_CONFIRM_PAYMENT"