import Image from '../../assets/jpg/product1.jpg'
export const productList = [
    {
        'id': 1,
        'file_host': 'http://localhost:8000',
        'file_path': '/images/product/',
        'file_name': 'cosmetic.jpg',
        'file_url': Image,
        'name': 'Laguna Gift Box',
        'price': 500000,
    },
    {
        'id': 2,
        'file_host': 'http://localhost:8000',
        'file_path': '/images/product/',
        'file_name': 'cosmetic.jpg',
        'file_url': Image,
        'name': 'Laguna Gift Box',
        'price': 500000,
    },
    {
        'id': 3,
        'file_host': 'http://localhost:8000',
        'file_path': '/images/product/',
        'file_name': 'cosmetic.jpg',
        'file_url': Image,
        'name': 'Laguna Gift Box',
        'price': 500000,
    },
    {
        'id': 4,
        'file_host': 'http://localhost:8000',
        'file_path': '/images/product/',
        'file_name': 'cosmetic.jpg',
        'file_url': Image,
        'name': 'Laguna Gift Box',
        'price': 500000,
    },
    {
        'id': 5,
        'file_host': 'http://localhost:8000',
        'file_path': '/images/product/',
        'file_name': 'cosmetic.jpg',
        'file_url': Image,
        'name': 'Laguna Gift Box',
        'price': 500000,
    },
    {
        'id': 6,
        'file_host': 'http://localhost:8000',
        'file_path': '/images/product/',
        'file_name': 'cosmetic.jpg',
        'file_url': Image,
        'name': 'Laguna Gift Box',
        'price': 500000,
    },
    {
        'id': 7,
        'file_host': 'http://localhost:8000',
        'file_path': '/images/product/',
        'file_name': 'cosmetic.jpg',
        'file_url': Image,
        'name': 'Laguna Gift Box',
        'price': 500000,
    },
    {
        'id': 8,
        'file_host': 'http://localhost:8000',
        'file_path': '/images/product/',
        'file_name': 'cosmetic.jpg',
        'file_url': Image,
        'name': 'Laguna Gift Box',
        'price': 500000,
    },
]

